### ISSUE TITLE
resetPassword page

### ISSUE THREAD

**Issue by jaxmann** [jaxmann/pmr-web#7]
needs new password field, confirm password, confirm button
send POST request with email (from url param), token (from url param), salt, hash

**Comment by jaxmann** [comment]
skeleton version of page done

**Comment by jaxmann** [comment]
@kevinchesser 
- what is the name of the route to send the reset details to? 
- the reset email should send them to /resetpassword with a token and their email

**Comment by kevinchesser** [comment]
@jaxmann Once they reset their password do we want to token to be used up? Or should they still be able to change their password as many times as they want with the link until the 30 minutes is up?

**Comment by kevinchesser** [comment]
The resetpassword endpoint is implemented.

**Comment by jaxmann** [comment]
@kevinchesser yeah use up the token i think. my post request after clicking reset password is sending a POST to /resetpassword with params of hash, salt, email, and token right?

**Comment by kevinchesser** [comment]
Okay I will have it use the token up. The params are token, email, passwordHash, and passwordSalt

**Comment by kevinchesser** [comment]
It now uses the token up. Close the issue once it is posting the data correctly.

**Comment by jaxmann** [comment]
it probably works
